version: '3.8'

services:
  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/src:/app/app
    ports:
      - 80:80
    depends_on:
      - db
    env_file:
      - config.env

  backend:
    build: ./backend/
    volumes:
      - ./backend/src:/app/app
    ports:
      - 80:80
    depends_on:
      - db
    env_file:
      - config.env
  
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data/
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    env_file:
      - config.env

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - config.env
    ports:
      - "5050:80"
    links:
      - "db:pgsql-server"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/config/:/etc/prometheus/
      - ./prometheus/prometheus_data:/prometheus
    ports:
     - 9090:9090

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/etc/grafana/dashboards/
      - ./grafana/grafana_data:/var/lib/grafana
    env_file:
      - config.env